"use client";

import { useEffect, useState } from "react";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { AdminShell } from "@/components/AdminShell";
import { db } from "@/lib/firebaseConfig";

type Seo = { title: string; description: string; keywords: string; agentSummary: string; canonicalUrl: string; ogTitle: string; ogDescription: string; ogImage: string; googleVerification: string; bingVerification: string };
const defaults: Seo = { title: "ByteBreach | Cybersecurity Training & Hands-On CTF Labs", description: "Master hands-on cybersecurity, ethical hacking, CCNA to CCIE networking tracks, and real-world CTF challenges. Join ByteBreach Security Academy for free.", keywords: "cybersecurity academy, CCNA practice labs, CCNP enterprise labs, CCIE network engineering, ethical hacking CTF, penetration testing labs, cyber defense XP, free cybersecurity training", agentSummary: "ByteBreach is a free, gamified cybersecurity academy covering CCNA, CCNP, CCIE, ethical hacking, packet analysis, penetration testing, and isolated CTF practice targets. Learners earn XP through Daily Challenges, study rooms, and flag captures while preparing for practical security work.", canonicalUrl: "https://bytebreach.in", ogTitle: "", ogDescription: "", ogImage: "", googleVerification: "", bingVerification: "" };
export default function SeoPage() {
  const [form, setForm] = useState(defaults); const [status, setStatus] = useState("");
  useEffect(() => { void getDoc(doc(db, "system", "seo")).then((snapshot) => snapshot.exists() && setForm({ ...defaults, ...(snapshot.data() as Partial<Seo>), keywords: Array.isArray(snapshot.data()?.keywords) ? snapshot.data()?.keywords.join(", ") : String(snapshot.data()?.keywords || defaults.keywords) })); }, []);
  const update = (key: keyof Seo, value: string) => setForm({ ...form, [key]: value });
  const save = async () => { await setDoc(doc(db, "system", "seo"), { ...form, keywords: form.keywords.split(",").map((item) => item.trim()).filter(Boolean) }, { merge: true }); setStatus("SEO and agentic discovery settings saved."); };
  const field = (key: keyof Seo, label: string) => <label className="block text-xs text-muted">{label}<input value={form[key]} onChange={(e) => update(key, e.target.value)} className="field mt-2 w-full"/></label>;
  return <AdminShell><div className="eyebrow text-cyan">Command center / discovery</div><h1 className="mt-2 text-3xl font-bold">SEO & Agentic Search</h1><p className="mt-2 text-sm text-muted">Control crawler metadata and the factual summary used by search agents.</p><div className="mt-8 grid max-w-5xl gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-line bg-panel p-5 lg:col-span-2"><h2 className="font-semibold">Search metadata</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{field("title", "Meta Title & Dynamic Site Slogan")}{field("canonicalUrl", "Canonical Base URL")}{field("description", "Meta Description")}{field("keywords", "Comma-Separated Keywords")}</div></section><section className="rounded-2xl border border-line bg-panel p-5 lg:col-span-2"><h2 className="font-semibold">LLM & agentic search directives</h2><textarea value={form.agentSummary} onChange={(e) => update("agentSummary", e.target.value)} className="field mt-4 min-h-40 w-full" placeholder="High-density platform summary for AI agents"/></section><section className="rounded-2xl border border-line bg-panel p-5"><h2 className="font-semibold">OpenGraph & Twitter</h2><div className="mt-4 space-y-4">{field("ogTitle", "OG Title")}{field("ogDescription", "OG Description")}{field("ogImage", "OG Image URL")}</div></section><section className="rounded-2xl border border-line bg-panel p-5"><h2 className="font-semibold">Verification</h2><div className="mt-4 space-y-4">{field("googleVerification", "Google Search Console Verification Code")}{field("bingVerification", "Bing Verification Token")}</div></section></div><button onClick={() => void save()} className="mt-5 rounded-xl bg-cyan px-5 py-3 text-xs font-bold text-ink">Save SEO Settings</button>{status && <div className="mt-3 text-xs text-cyan">{status}</div>}</AdminShell>;
}
